sudo: required
services:
  - docker

before_install:
  - docker build -t ewfnz/docker-travisci-aws:development -f Dockerfile.dev .

script:
  - docker run ewfnz/docker-travisci-aws:development yarn test -- --coverage
